name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Express docker image build test
        run: |
          docker build -t vdanbooru-express-image ./express

      - name: Build prod test
        run: |
          dd of=.env.production << EOF
          NODE_ENV=production
          REACT_APP_BASE_URL_DEV=${{secrets.REACT_APP_BASE_URL_DEV}}
          REACT_APP_ROUTER_BASENAME=${{secrets.REACT_APP_ROUTER_BASENAME}}
          EOF
          yarn && CI=false yarn build:prod
