name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy express to heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'vdanbooru-express-server'
          heroku_email: 'linengcao@yahoo.com'
          appdir: 'express'
          usedocker: true

      - name: Build prod test
        run: |
          dd of=.env.production << EOF
          NODE_ENV=production
          REACT_APP_BASE_URL_DEV=${{secrets.REACT_APP_BASE_URL_DEV}}
          REACT_APP_ROUTER_BASENAME=${{secrets.REACT_APP_ROUTER_BASENAME}}
          EOF
          yarn && CI=false yarn build:prod
