name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy express docker container to heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'vdanbooru-express-server'
          heroku_email: 'linengcao@yahoo.com'
          appdir: 'express'
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production

      - name: Build frontend & Deploy in build branch
        run: |
          dd of=.env.production << EOF
          NODE_ENV=production
          REACT_APP_BASE_URL_DEV=${{secrets.REACT_APP_BASE_URL_DEV}}
          REACT_APP_ROUTER_BASENAME=${{secrets.REACT_APP_ROUTER_BASENAME}}
          EOF
          yarn && yarn build:prod

      - name: Deploy & host on build branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: build
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
