name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Depoly
        run: |
          dd of=.env.production << EOF
          NODE_ENV=production
          REACT_APP_BASE_URL_DEV=${{secrets.REACT_APP_BASE_URL_DEV}}
          REACT_APP_ROUTER_BASENAME=${{secrets.REACT_APP_ROUTER_BASENAME}}
          EOF
          yarn && CI=false yarn build:prod

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: demo
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
